### ISSUE TITLE
Incompatible with FoF/OAuth

### ISSUE THREAD

**Issue by SanketDube** [FriendsOfFlarum/disposable-emails#4]
Signing up via OAuth:
1. Signup. *Signup form appears*
2. Login in via Google. *Taken to a new window to confirm user*
3. *User is authenticated via Google and comes back to Sign Up Page*
4. Email field is greyed out and the form asks for the desired Username *user entered a username*
5. *red bar pop saying "You may not use a disposable email".

I believe this is not the intended behaviour.

**Comment by dsevillamartin** [comment]
Hm yeah, this means this extension doesn't really work with any OAuth ext (including fof/oauth). Whoops!

**Comment by luceos** [comment]
please re-enable on discuss once fixed and updated (or mention me on discord to get that done)

**Comment by imorland** [comment]
Fixed with `1.0.0`

cc @luceos https://discuss.flarum.org/d/20457-friendsofflarum-disposable-emails/28
